# Generated by Django 5.0.7 on 2024-07-12 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.ativo')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_inferior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_superior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicidade', models.IntegerField(help_text='Periodicidade em minutos')),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.ativo')),
            ],
        ),
    ]
