# Generated by Django 3.2 on 2024-07-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='limite_inferior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ativo',
            name='limite_superior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ativo',
            name='periodicidade',
            field=models.IntegerField(default=0, help_text='Periodicidade em minutos'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ParametroAtivo',
        ),
    ]
